### ISSUE TITLE
Error when building fastdet

### ISSUE THREAD

**Issue by bnt2025** [swkrueger/Thrifty#1]
Hi there I am unable to compile fastdet

On a Pi 3 Raspbian Stretch 4.9.41-v7+ 
After following the pi3 install guide
When trying to `make` fastdet

```bash
[ 20%] Building CXX object CMakeFiles/fastdet.dir/corr_detector.cpp.o
/tmp/Thrifty/fastdet/corr_detector.cpp: In member function ‘CorrDetection CorrDetector::detect(const std::complex<float>*, float)’:
/tmp/Thrifty/fastdet/corr_detector.cpp:153:35: error: cannot convert ‘unsigned int*’ to ‘uint16_t* {aka short unsigned int*}’ in argument passing
             stop_idx_ - start_idx_);
                                   ^
CMakeFiles/fastdet.dir/build.make:62: recipe for target 'CMakeFiles/fastdet.dir/corr_detector.cpp.o' failed
make[2]: *** [CMakeFiles/fastdet.dir/corr_detector.cpp.o] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/fastdet.dir/all' failed
make[1]: *** [CMakeFiles/fastdet.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by swkrueger** [comment]
Hey. Thank you for your interest in Thrifty!

What version of libvolk do you have installed? If I remember correctly, the version of libvolk that is in the Raspbian repository is rather old and has a slightly different interface then the newer one in the upstream Debian repository. You can try to install a newer version of libvolk from the upstream Debian repository, as described in more detail [here](https://github.com/swkrueger/Thrifty/blob/master/rpi/installation.md#install-packages) (you'll probably want to replace `jessie-backports` with `stretch`) or you can compile it from source.

Alternatively, it might work to simply change the code in `fastdet/corr_detector.cpp` to match the old volk interface by changing the cast on line 151 of `corr_derector.cpp` to `uint16_t*`, i.e. change that line to `(uint16_t*)&peak_idx,`. The program will run a bit slower since the old version of volk has basically no kernels for the RPi3's architecture.

**Comment by bnt2025** [comment]
Hi there, 
Thanks for the reply. I tried again on the image you recommended as well but had the same issue. My versions are 
```bash
# apt-cache policy libvolk1.3 libvolk1-dev
libvolk1.3:
  Installed: 1.3-1~bpo8+1
  Candidate: 1.3-1~bpo8+1
  Version table:
 *** 1.3-1~bpo8+1 0
        100 /var/lib/dpkg/status
libvolk1-dev:
  Installed: 1.3-1~bpo8+1
  Candidate: 1.3-1~bpo8+1
  Version table:
 *** 1.3-1~bpo8+1 0
        100 /var/lib/dpkg/status

```

I ended up modifying the line as you recommended and it managed to compile and install.
